### ISSUE TITLE
Consider changing the name of the repo to something that identifies that it's related to Azure Cognitive Service Speech

### ISSUE THREAD

**Issue by paulomorgado** [microsoft/batch-processing-kit#2]
batch processing kit is very broad in the context of Microsoft.

**Comment by anwald** [comment]
The framework is a generic batch processing library that is not confined to Azure Cognitive Services. That's just currently the only example. But the framework and the example are split into separate modules, and it's a matter of convenience that they are in the same repo. It's intended for any use case where there are local or remote worker process slaves. There will be forthcoming examples showing much more mundane sort of batch processing.
